### ISSUE TITLE
`Display domain name` option breaking the app

### ISSUE THREAD

**Issue by mateo-m** [Bonfida/jabber-mobile-app#2]
When tapping the `Display domain name` option, a blank page shows up and there's no way to go back.

Demo :
https://user-images.githubusercontent.com/23667794/143574706-e06728bd-1027-4fab-a7a2-28c3fbef6cce.MOV

**Comment by dr497** [comment]
I cannot reproduce on my end. Can you try to clear your cache? I think an upgrade broke the type of one cache key and it can explain it

**Comment by mateo-m** [comment]
Clearing the cache seems to fix it, thanks !
What is this cache key thing you're talking about ?

**Comment by dr497** [comment]
The `knownReceiver` cache key was changed from `string` to `string[]` https://github.com/Bonfida/jabber-mobile-app/blob/master/utils/name-service.tsx#L38 when the concept of favorite domain name (`:fdn:`) was introduced

**Comment by mateo-m** [comment]
Alright, thanks for explaining.
