### ISSUE TITLE
unsupported wallet seed phrase 

### ISSUE THREAD

**Issue by 1Ajay2** [Bonfida/jabber-mobile-app#4]
Jabber wallet account 4vDGu2qjSvuoM8BcMsTtQ65YTKFmp422v1Mio8v4BEjx has unsupported seed for sollet.io and unable to restore it

this could be a glitch, the seed has a typo in one word and unable to restore in sollet but when typo is corrected the restored wallet has no derivable path that lead to   4vDGu2qjSvuoM8BcMsTtQ65YTKFmp422v1Mio8v4BEjx

**Comment by dr497** [comment]
Wallets created in Jabber should be restored in Sollet using the derivation path `m/44'/501'/0'/0'`

**Comment by 1Ajay2** [comment]
thanks for your response sir actually I'm facing issue with seed phrase itself the displayed seed is unsupported with sollet, possibly a glitch I have attached a video link https://twitter.com/ajaykum38140921/status/1470041827428372488

**Comment by dr497** [comment]
I have tried with a wallet generated by Jabber and it can be restored on Sollet.

Mnemoics are generated the same on Jabber and Sollet:

- https://github.com/Bonfida/jabber-mobile-app/blob/master/utils/wallet.native.tsx#L138
- https://github.com/project-serum/spl-token-wallet/blob/master/src/utils/wallet-seed.js

**Comment by 1Ajay2** [comment]
To make sure my wallet is not the only one I too checked with new wallet it restored without any trouble except 4vDGu2qjSvuoM8BcMsTtQ65YTKFmp422v1Mio8v4BEjx

I am more than willing to help to give all imp details to get to the bottom of the Issue It has 5 $fida which I received from attending first AMA on Jabber, kindly arrange a private channel so I can send details sir

I will lose my wallet by doing so but I have to trust :)

**Comment by dr497** [comment]
I added a way to retrieve the private key directly instead of the mnemonic https://github.com/Bonfida/jabber-mobile-app/pull/3/commits/9a6585935db56dc9dbc5f327d396f32bbf8f7479

This will be merged Wednesday so you will be able to retrieve directly the private key

**Comment by 1Ajay2** [comment]
that should resolve it, thanks for your support! :) waiting for Wednesday

**Comment by 1Ajay2** [comment]
finally I am able to restore my wallet using key thanks for necessary update sir, though I am still seeing old seed which was unsupported on sollet, With the key I restored on solflare like a cake  also the new UI looks awesome!

**Comment by dr497** [comment]
Thanks for keeping me posted and I am glad to know it's resolved 🙌
